baseurl = "/"
languageCode = "en-us"
title = "JJ Handyman Services"

[params]
  description = "Handyman services, moving, and professional cleaning in the greater Twin Cities metro area."

[[menu.main]]
    name = "Services"
    url  = "/services"
    weight = 4

[[menu.main]]
    name = "Gallery"
    url  = "/gallery"
    weight = 3
    
[[menu.main]]
    name = "Testimonials"
    url  = "/testimonials"
    weight = 2
    
[[menu.main]]
    name = "Schedule Appointment"
    url  = "/contact"
    weight = 1
