baseurl = "/"
languageCode = "en-us"
title = "JJ Handyman Services"

[params]
  description = "Handyman services, moving, cleaning in the greater Twin Cities metro area."

[[menu.main]]
    name = "Services"
    url  = "/services"
    weight = 1

[[menu.main]]
    name = "Gallery"
    url  = "/gallery"
    weight = 1
    
[[menu.main]]
    name = "Testimonials"
    url  = "/testimonials"
    weight = 1
    
[[menu.main]]
    name = "Contact"
    url  = "/contact"
    weight = 1
